### ISSUE TITLE
KeyError: 'mining_runs'

### ISSUE THREAD

**Issue by andrefff9** [x-actly/Eve-Online-Mining-Bot#21]
hello,  when i try to start the main.py, i get the following issue: 

Traceback (most recent call last):
  File "c:\Users\andr\Desktop\Eve-Online-Mining-Bot\main.py", line 107, in <module>
    entry.insert(tk.END, config['SETTINGS']['mining_runs'])
                         ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\configparser.py", line 1273, in __getitem__
    raise KeyError(key)
KeyError: 'mining_runs'

what could be the cause of this?

**Comment by x-actly** [comment]
Fixed a KeyError occurring when accessing the "mining_runs" key in the "SETTINGS" section of the configuration file (config.properties). The issue was resolved by ensuring that the configuration file contains the necessary key-value pair for "mining_runs" under the "SETTINGS" section.

it should work now... fly safe ;-)
